DROP DATABASE IF EXISTS `exo_contacts`;
CREATE DATABASE `exo_contacts` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE pays (
  iso_3 VARCHAR(3) NOT NULL AUTO_INCREMENT,
  iso_2 VARCHAR(2) NOT NULL,
  nom VARCHAR(70) NOT NULL,
  PRIMARY KEY (iso_3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

